{
 "title": "Docker Dashboard",
 "description": "Docker Monitoring Template",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(container_cpu_usage_seconds_total{job=\"cadvisor\"}, instance)"
   },
   {
    "name": "port",
    "label": "port",
    "query": "label_values(container_cpu_usage_seconds_total{job=\"cadvisor\"}, instance)"
   },
   {
    "name": "nodeport",
    "label": "nodeport",
    "query": "label_values(node_boot_time{job=\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal{instance=~\"$node:$nodeport\"}) - sum(node_memory_MemFree{instance=~\"$node:$nodeport\"}+node_memory_Buffers{instance=~\"$node:$nodeport\"}+node_memory_Cached{instance=~\"$node:$nodeport\"}) ) / sum(node_memory_MemTotal{instance=~\"$node:$nodeport\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\",instance=~\"$node:$port\"}[1m] ) )) / count(node_cpu{mode=\"system\",instance=~\"$node:$nodeport\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{instance=~\"$node:$port\"} - container_fs_usage_bytes{instance=~\"$node:$port\"}) / sum(container_fs_limit_bytes{instance=~\"$node:$port\"})"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\",instance=~\"$node:$port\"}[1m])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",instance=~\"$node:$port\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",instance=~\"$node:$port\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\",instance=~\"$node:$port\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}